# for an example project named 'nextjs-tailwind-starter'

steps:
  # build the container images
  - name: "gcr.io/cloud-builders/docker"
    args:
      ["build", "-t", "gcr.io/$PROJECT_ID/nextjs-tailwind-starter", "./client"]

  # push the container images to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/nextjs-tailwind-starter"]

  # Deploy container images to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "nextjs-tailwind-starter",
        "--image",
        "gcr.io/$PROJECT_ID/nextjs-tailwind-starter",
        "--region",
        "us-central1",
        "--platform",
        "managed",
        "--quiet",
        "--allow-unauthenticated",
      ]
images:
  - gcr.io/$PROJECT_ID/nextjs-tailwind-starter
